micronaut:
  application:
    name: balance
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:mysql://localhost:3306/balance
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Rurik123Rems
    dialect: MYSQL
