micronaut:
  application:
    name: balance
    rateservice: http://data.fixer.io/api/latest?access_key=6cb34ef14beb2ad5c1dcc06c69d814d4
  security:
    login: srzaev
    password: 7351355@mail.ru
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
#    url: jdbc:mysql://balance.co1tlyp5pr7f.eu-north-1.rds.amazonaws.com:3306/balance
    url: jdbc:mysql://localhost:3306/balance
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Rurik123Rems
    dialect: MYSQL
views:
    #thymeleaf properties (thymeleaf is enabled by default; just to make sure)
 thymeleaf:
  enabled: true
router:
 static-resources:
  main:
   enabled: true
   paths: "classpath:views"
        #bind views folder to main path
   mapping: "/main/**"